### ISSUE TITLE
A solution to scraping

### ISSUE THREAD

**Issue by SabreBleu** [duolicious/duolicious-backend#295]
In case you haven't seen yet, the data on the site is being mass scraped. 4chan's /g/entoomen made a scraper : https://duoleak.acid.im/ & a team of social science researchers from the EU also used one : https://archive.org/details/duolicious_analysis/mode/1up . Tbf, its just things you put on your public profile and even Tinder has struggled fighting scrapers. Hindering and getting rid of these bots could not only clear the honeypot allegations but also would marginally improve performance.

**Comment by duogenesis** [comment]
Working on it in https://github.com/duolicious/duolicious-backend/pull/296

**Comment by duogenesis** [comment]
tbh, I can understand the /g/entooman but I'm pretty salty about the social scientists. Duolicious' [terms](https://duolicious.app/terms/) say:

>When using the Service, you commit to the following:
>* [you must not] act in a way that harms the reputation or functionality Duolicious.

But they say in the paper that they put so much load on the server that they got rate limited. And contrary to what they say in the paper, they never asked for my permission. Then they're probably going to use the ill-gotten data to write a hit-piece mischaracterizing Duolicious as being for rightists only. It's not. If it were designed for people with homogeneous political views, there'd be no point asking about your political views in the personality test. /rant
