### ISSUE TITLE
Image upload fails if resolution is too high

### ISSUE THREAD

**Issue by Johgaaa** [duolicious/duolicious-backend#318]
I tried to upload a couple images, but the request kept returning with a 400 Bad Request. Finally figured out it's because of the resolution. The Images I originally tried to upload were 5456 x 3632 pixels and wouldn't upload even when compressed down to ~5mb.
Once I scaled them down to about 1300 x 900 px the upload worked.

**Comment by duogenesis** [comment]
Thanks for raising this ticket. It's been closed by https://github.com/duolicious/duolicious-frontend/pull/477
