### ISSUE TITLE
DUOLICIOUS!!! FIX MESSAGE NOTIFICATIONS AND MY LIFE IS YOURS!!! 

### ISSUE THREAD

**Issue by Wolfman31337** [duolicious/duolicious-backend#426]
What I assume to maybe be women are texting me and I can't reply because the dm's won't load. I beg of you please fix this issue I'm dieing over here.

**Comment by duogenesis** [comment]
https://github.com/duolicious/duolicious-backend/pull/423 really harmed performance but I've rolled it back for now. I'll attempt to deploy a faster version tomorrow.

**Comment by Wolfman31337** [comment]
Thanks bro
